---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  name: "Build SVM: {{ svm_name }}"

  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      use_rest: auto
  vars_files:
    - ./svm_iscsi_vars_draft.yml
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter the NetApp Admin Password"
      private: true
      confirm: true

  tasks:

  - name: Create SVM with iSCSI protocol
    na_ontap_svm:

