---
- name: This Playbook is for Practice
  hosts: localhost
  gather_facts: false

  collections:
    - netapp.ontap

  vars_files:
    - ./play2_vars.yml
  
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: cluster2.demo.netapp.com
      username: admin
      password: Netapp1!
      validate_certs: false
      https: true
  
  tasks:
    - name: Create SVM and Enable protocol
      netapp.ontap.na_ontap_svm:
        state: present
        name: "{{ svm }}"
        hostname: cluster2.demo.netapp.com
        username: admin
        password: Netapp1!
        validate_certs: false
        https: true
        services:
          nfs:
            allowed: true
            enabled: true

          iscsi:
            allowed: true
            enabled: true
    - name: Create a FlexVol
      netapp.ontap.na_ontap_volume:
        state: present
        vserver: "{{ svm }}"
        name: "{{ volname }}"
        aggregate_name: "{{ aggr }}"
        size: 1
        size_unit: gb
        junction_path: "/{{ volname }}"
        policy: "default"
        type: "rw"
        volume_security_style: unix

    - name: Creation of Lif
      netapp.ontap.na_ontap_interface:
        interface_name: "lif_nfs_01"
        address: "{{ address }}"
        netmask: "255.255.255.0"
        home_port: "e0e"
        home_node: "cluster2-01"
        vserver: "{{ svm }}"
        service_policy: "default-data-files"
        #data_protocol: "ntfs"
    
    - name: Add rules in export-policy
      netapp.ontap.na_ontap_export_policy_rule:
        state: present
        policy_name: "default"
        client_match: "{{ client }}" 
        rw_rule: "any"
        ro_rule: "any"
        protocol: "nfs"
        vserver: "{{ svm }}"
        rule_index: 2





